apiVersion: batch/v1
kind: Job
metadata:
  name: revel-batch
spec:
  parallelism: 1
  template:
    metadata:
      labels:
        app: revel-batch
    spec:
      restartPolicy: OnFailure
      containers:
        - name: revel
          image: ${IMAGE_NAME}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 0.2
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 128Mi
          ports:
            - containerPort: 50190
              protocol: TCP
          tty: true
          stdin: true
          command: ["ash","-c","${CMD}"]
          env:
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-staging-db-credentials
                  key: username
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-staging-db-credentials
                  key: password
            - name: FRONTEND_DB_HOST
              value: "127.0.0.1"
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_NAME
              value: "staging_backend"
            - name: UPLOADED_FILE_BUCKET
              value: "staging-uploaded-files-store"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/go/src/github.com/RonieGSS/k8_jenkins_go/src/revel/conf/storage-reader.json"
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          resources:
            limits:
              cpu: 0.2
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 128Mi
          command: ["/cloud_sql_proxy",
                    "-instances=${PROJECT}:asia-northeast1:revel-staging-instance=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      - name: cloudsql
        emptyDir:
  backoffLimit: 6