apiVersion: v1
kind: Service
metadata:
  name: cakephp-node-port
spec:
  type: NodePort
  selector:
    app: cakephp-staging-deployment
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
