apiVersion: apps/v1
kind: Deployment
metadata:
  name: revel-staging-deployment
  labels:
    app: revel-staging-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: revel-staging-deployment
  template:
    metadata:
      labels:
        app: revel-staging-deployment
    spec:
      containers:
        - name: revel
          image: ${IMAGE_NAME}
          imagePullPolicy: Always
          ports:
            - containerPort: 50190
              protocol: TCP
          resources:
            limits:
              cpu: 0.2
              memory: 500Mi
            requests:
              cpu: 50m
              memory: 128Mi
          envFrom:
            - secretRef:
                name: revel-secret
 
          readinessProbe:
            httpGet:
              path: /public/bundle.js
              port: 50190
            initialDelaySeconds: 5
            periodSeconds: 5
                
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          resources:
            limits:
              cpu: 0.2
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 128Mi
          command: ["/cloud_sql_proxy",
                    "-instances=${PROJECT}:asia-northeast1:revel-staging-instance=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      - name: cloudsql
        emptyDir:
