apiVersion: v1
kind: Service
metadata:
  name: revel-node-port
spec:
  type: NodePort
  selector:
    app: revel-staging-deployment
  ports:
    - port: 80
      targetPort: 50190
      protocol: TCP
